CREATE DATABASE olcha;


CREATE TABLE IF NOT EXISTS categories
(
    id            SERIAL PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL
);


INSERT INTO categories (category_name)
VALUES ('Smartfonlar'),
       ('Kompyuter va texnika'),
       ('Maishiy texnika'),
       ('Kiyim-kechak'),
       ('Aksessuarlar'),
       ('Bolalar mahsulotlari'),
       ('Sport va dam olish'),
       ('Kitoblar'),
       ('Qurilish va taʼmirlash');

CREATE TABLE IF NOT EXISTS products
(
    id            SERIAL PRIMARY KEY,
    products_name VARCHAR(255) NOT NULL,
    description   TEXT         NOT NULL,
    price         INTEGER      NOT NULL,
    is_available  BOOLEAN   DEFAULT true,
    category_id   INTEGER      NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE products;


INSERT INTO products
    (products_name, description, price, category_id)
VALUES ('Samsung Galaxy S23', 'Yuqori darajadagi Android smartfon, kuchli kamera va tezkor ishlash', 12000000, 1),
       ('Apple iPhone 14', 'Apple iOS smartfon, sifatli kamera va optimizatsiya, yaxshi ishlash', 13000000, 1),
       ('Xiaomi Redmi Note 12', 'Byudjet Android smartfon, katta ekran va uzoq umrlik batareya', 2800000,  1),
       ('Huawei Y9S', 'O‘rtacha darajadagi smartfon, yaxshi selfie kamera bilan', 3500000, 1),
       ('Realme 9 Pro', 'Qattiq protsessor bilan o‘rtacha narxdagi smartfon', 4000000, 1),
       ('Vivo V25e', 'Moda smartfon, yaxshi dizayn va kamera', 6000000, 1),
       ('Honor X7b', 'Sodda smartfon, yaxshi narx‑sifat nisbati', 2200000, 1),
       ('Samsung Galaxy S23 Ultra', 'Flagman smartfon, ajoyib kamera va kuchli protsessor', 16500000, 1),
       ('iPhone 14 Pro Max', 'Yuqori darajadagi Apple smartfon, 120Hz ekran va kuchli chip', 18000000, 1),
       ('Xiaomi 13', 'Premium Android smartfon, tezkor ishlash va uzoq batareya', 9500000, 1),
       ('Realme GT 3', 'O‘yinlar uchun qulay, kuchli protsessor va AMOLED ekran', 5500000,  1),
       ('Vivo X90', 'Moda smartfon, katta ekran va yaxshi kamera', 7500000, 1),
       ('Huawei P50 Pro', 'Kamera va foto imkoniyatlari ajoyib', 8500000, 1),
       ('Honor 90', 'Byudjet va sifat nisbati yaxshi', 4500000, 1),
       ('Samsung Galaxy S23 Ultra', 'Flagman smartfon, ajoyib kamera va kuchli protsessor', 16500000, 1),
       ('iPhone 14 Pro Max', 'Yuqori darajadagi Apple smartfon, 120Hz ekran va kuchli chip', 18000000, 1),
       ('Xiaomi 13', 'Premium Android smartfon, tezkor ishlash va uzoq batareya', 9500000, 1),
       ('Realme GT 3', 'O‘yinlar uchun qulay, kuchli protsessor va AMOLED ekran', 5500000, 1),
       ('Vivo X90', 'Moda smartfon, katta ekran va yaxshi kamera', 7500000, 1),
       ('Huawei P50 Pro', 'Kamera va foto imkoniyatlari ajoyib', 8500000, 1),
       ('Honor 90', 'Byudjet va sifat nisbati yaxshi', 4500000, 1),
       ('Samsung Galaxy S22', 'Oldingi avlod premium Android smartfon, yaxshi kamera va tezkor ishlash', 9500000, 1),
       ('iPhone 13', 'Apple iOS smartfon, yaxshi ishlash va barqaror tizim', 12000000, 1),
       ('Xiaomi 12T', 'Yuqori tezlik va uzoq batareya bilan byudjet variant', 6200000, 1),
       ('Realme 10 Pro+', 'O‘yin va media uchun qulay smartfon', 4900000, 1),
       ('Vivo Y100', 'Moda va kundalik ishlash uchun smartfon', 3800000, 1),
       ('Huawei Nova 10', 'Kamera imkoniyatlari yaxshi, zamonaviy dizayn', 5500000, 1),
       ('Honor Magic5', 'Flagman smartfon, yuqori ishlash va ajoyib dizayn', 8800000, 1),
       ('Samsung Galaxy A53', 'O‘rta sinf Android smartfon, uzoq batareya', 4200000, 1),
       ('Xiaomi Poco X5 Pro', 'Byudjet va kuchli protsessor, yaxshi ekran', 4000000, 1),
       ('Realme Narzo 60', 'Byudjet smartfon, kundalik ishlash uchun ideal', 2800000, 1),
       ('Dell Inspiron 15', 'Ofis va kundalik ishlash uchun noutbuk', 7500000, 2),
       ('HP Pavilion 14', 'Kuchli protsessorli noutbuk, ishlash va o‘yinlar uchun', 8200000, 2),
       ('Lenovo ThinkPad X1', 'Biznes noutbuk, mustahkam va uzoq umr', 15000000, 2),
       ('Asus ROG Strix', 'O‘yinlar uchun maxsus noutbuk, kuchli GPU bilan', 18000000, 2),
       ('Apple MacBook Air M2', 'Yuqori samarali Apple noutbuk, engil va tezkor', 20000000, 2),
       ('Acer Aspire 5', 'Byudjet noutbuk, kundalik ishlash uchun ideal', 6000000, 2),
       ('MSI Modern 15', 'Ofis va o‘yinlar uchun qulay noutbuk', 9000000, 2),
       ('HP EliteBook 840', 'Biznes va professional ishlash uchun noutbuk', 14000000, 2),
       ('Lenovo IdeaPad 3', 'O‘rta sinf noutbuk, yaxshi narx-sifat nisbati', 5000000, 2),
       ('Apple MacBook Pro M1', 'Flagman Apple noutbuk, kuchli chip va yuqori samaradorlik', 25000000, 2),
       ('Asus VivoBook 15', 'O‘rta sinf noutbuk, kundalik ishlash uchun ideal', 5800000, 2),
       ('Dell XPS 13', 'Premium noutbuk, kuchli protsessor va zamonaviy dizayn', 18000000, 2),
       ('Lenovo Legion 5', 'O‘yinlar uchun kuchli noutbuk, tezkor GPU bilan', 14500000, 2),
       ('Acer Nitro 5', 'O‘yinlar va multimedia uchun byudjet noutbuk', 9500000, 2),
       ('HP Omen 16', 'O‘yinlar uchun yuqori samarali noutbuk, kuchli GPU', 16000000, 2),
       ('Apple iMac 24"', 'Desktop kompyuter, kuchli Apple chip va yuqori samaradorlik', 25000000, 2),
       ('MSI GF63 Thin', 'O‘yinlar va ofis ishlari uchun qulay noutbuk', 10000000, 2),
       ('Asus TUF Gaming F15', 'O‘yinlar uchun bardoshli va kuchli noutbuk', 13500000, 2),
       ('Lenovo Yoga Slim 7', 'Yengil va qulay noutbuk, kundalik ishlash uchun', 8500000, 2),
       ('HP Spectre x360', 'Premium noutbuk, ajoyib dizayn va ishlash', 17000000, 2),
       ('Samsung Kir yuvish mashinasi', 'Avtomatik kir yuvish mashinasi, 7 kg yuk sig‘imi bilan', 4200000, 3),
       ('LG Muzlatkich', '2 eshikli sovutgich, katta hajm va energiya samarali', 5300000, 3),
       ('Bosch Mikser', 'Qulay oshxona mikseri, aralashtirish va urish funktsiyalari bilan', 1200000, 3),
       ('Philips Toaster', '2 teshikli tost pech, tez va qulay', 500000, 3),
       ('Samsung Qaynatgich', 'Elektrik choynak, tez qaynatish va avtomatik o‘chish', 350000, 3),
       ('LG Konditsioner', 'Xonani tez sovutadigan va energiya samarali konditsioner', 7800000, 3),
       ('Bosch Vakuumli Changyutgich', 'Kuchli changyutgich, uzoq kabel va turli aksessuarlar bilan', 2600000, 3),
       ('Philips Blender', 'Katta hajmli blender, smuzi va sho‘rva tayyorlash uchun', 1500000, 3),
       ('Samsung Mikrotolqinli Pech', 'Tez qizdirish va pishirish imkoniyati bilan', 3200000, 3),
       ('LG Kir yuvish + Quritish', '2 birida kir yuvish va quritish mashinasi, yuqori samaradorlik', 9000000, 3),
       ('Erkaklar futbolkasi', 'Qulay va zamonaviy futbolka, kundalik kiyish uchun', 250000, 4),
       ('Ayollar bluzkasi', 'Yengil va nafis bluzka, ofis va kundalik uchun', 320000, 4),
       ('Erkaklar ko‘ylagi', 'Ofis va rasmiy tadbirlar uchun klassik ko‘ylak', 550000, 4),
       ('Ayollar ko‘ylagi', 'Moda va qulaylikni uyg‘unlashtirgan ko‘ylak', 480000, 4),
       ('Erkaklar jinsiligi', 'Sifatli va bardoshli jinsilar, kundalik foydalanish uchun', 600000, 4),
       ('Ayollar yubkasi', 'Elegant va qulay yubka, har xil holatlar uchun', 450000, 4),
       ('Erkaklar kostyumi', 'Rasmiy va tadbirlar uchun klassik kostyum', 1200000, 4),
       ('Ayollar kostyumi', 'Ofis va biznes uchun zamonaviy kostyum', 1100000, 4),
       ('Erkaklar sport kiyimi', 'Jismoniy mashqlar va sport uchun qulay kiyim', 350000, 4),
       ('Ayollar sport kiyimi', 'Trenajyor va fitness uchun qulay kiyim', 370000, 4),
       ('Erkaklar futbolka uzun', 'Yengil va kundalik futbolka', 280000, 4),
       ('Ayollar tunikasi', 'Moda va qulaylikni uyg‘unlashtirgan tunika', 400000, 4),
       ('Erkaklar kurtkasi', 'Bardoshli va sovuqdan himoya qiluvchi kurtka', 950000, 4),
       ('Ayollar kurtkasi', 'Zamonaviy va qulay kurtka, har xil ob-havo uchun', 900000, 4),
       ('Erkaklar sviter', 'Yoz va bahor uchun yengil sviter', 320000, 4),
       ('Ayollar sviter', 'Moda va qulay sviter, har kuni kiyish uchun', 350000, 4),
       ('Erkaklar shorti', 'Yozgi kundalik kiyim, qulay short', 220000, 4),
       ('Ayollar shorti', 'Yengil va zamonaviy short, yozgi kiyim', 250000, 4),
       ('Erkaklar jinsi kurtka', 'Bardoshli va moda jinsi kurtka', 850000, 4),
       ('Ayollar jinsi kurtka', 'Moda va kundalik kiyish uchun jinsi kurtka', 820000, 4),
       ('Erkaklar trikotaj sviter', 'Qulay va issiq trikotaj sviter', 300000, 4),
       ('Ayollar trikotaj sviter', 'Moda va issiq trikotaj sviter', 330000, 4),
       ('Erkaklar palto', 'Kuz va qish uchun klassik palto', 1250000, 4),
       ('Ayollar palto', 'Zamonaviy va issiq palto', 1300000, 4),
       ('Erkaklar futbolka sport', 'Jismoniy mashqlar uchun sport futbolka', 260000, 4),
       ('Erkaklar soati', 'Elegant va zamonaviy erkaklar soati', 450000, 5),
       ('Ayollar soati', 'Moda va nafis ayollar soati', 420000, 5),
       ('Kamarlar', 'Turli rang va materialdagi kamarlar', 120000, 5),
       ('Kuzgi shapka', 'Issiq va qulay kuzgi shapka', 180000, 5),
       ('Ayollar sumkasi', 'Katta hajmli va moda sumka', 350000, 5),
       ('Erkaklar sumkasi', 'Ofis va kundalik ishlash uchun sumka', 380000, 5),
       ('Aylana bilaguzuk', 'Moda va nafis bilaguzuk', 150000, 5),
       ('Sirg‘a', 'Ayollar uchun moda sirg‘a', 80000, 5),
       ('Ayollar sharf', 'Issiq va zamonaviy sharf', 200000, 5),
       ('Erkaklar sharf', 'Klassik va qulay sharf', 220000, 5),
       ('Kaptan va kepka', 'Turli rang va dizayndagi kepkalar', 120000, 5),
       ('Ayollar kamarli soat', 'Moda va nafis dizayn', 450000, 5),
       ('Erkaklar charm kamar', 'Klassik va mustahkam charm kamar', 300000, 5),
       ('Ayollar charm sumka', 'Moda va kundalik ishlash uchun sumka', 400000, 5),
       ('Sport aksessuarlari', 'Trenajyor va sport uchun turli aksessuarlar', 180000, 5),
       ('Ayollar kosmetik sumkasi', 'Kichik va qulay kosmetik sumka', 150000, 5),
       ('Erkaklar sport soati', 'Trenajyor va sport uchun qulay soat', 350000, 5),
       ('Ayollar charm bilaguzuk', 'Moda va nafis bilaguzuk', 200000, 5),
       ('Erkaklar charm soat', 'Klassik dizayn va sifatli soat', 500000, 5),
       ('Ayollar shapka va kepka', 'Moda va qulay dizayn', 180000, 5),
       ('O‘yinchoq mashina', 'Bolalar uchun rangli o‘yinchoq mashina', 150000, 6),
       ('O‘yinchoq qo‘g‘irchoq', 'Yumshoq va xavfsiz qo‘g‘irchoq', 120000, 6),
       ('Bolalar stul', 'Kichik yoshdagi bolalar uchun qulay stul', 200000, 6),
       ('O‘yinchoq bloklar', 'Ta’limiy va kreativ bloklar', 180000, 6),
       ('O‘yinchoq cho‘q', 'Rangli va xavfsiz cho‘q', 100000, 6),
       ('Bolalar kitobi', 'Rangli rasmlar bilan bolalar kitobi', 90000, 6),
       ('Bolalar poyabzali', 'Qulay va xavfsiz poyabzal', 250000, 6),
       ('Bolalar futbolkasi', 'Yengil va qulay futbolka', 120000, 6),
       ('Bolalar yubkasi', 'Moda va qulay yubka', 150000, 6),
       ('Bolalar sport kiyimi', 'Trenajyor va sport uchun qulay kiyim', 180000, 6),
       ('Bolalar kiyimi to‘plami', 'Futbolka va short to‘plami', 300000, 6),
       ('O‘yinchoq piano', 'Bolalar uchun musiqiy piano', 220000, 6),
       ('Bolalar aravasi', 'Kichik yoshdagi bolalar uchun qulay arava', 850000, 6),
       ('Bolalar skeytbord', 'Yosh bolalar uchun xavfsiz skeytbord', 400000, 6),
       ('Bolalar velosipedi', 'Qulay va xavfsiz bolalar velosipedi', 700000, 6),
       ('Futbol to‘pi', 'Professional sifatli futbol to‘pi', 300000, 7),
       ('Basketbol to‘pi', 'Yuqori sifatli basketbol to‘pi', 320000, 7),
       ('Stol tennis raketkasi', 'Trenajyor va o‘yin uchun raketka', 180000, 7),
       ('Velosiped uchun shlem', 'Xavfsizlik uchun mustahkam shlem', 250000, 7),
       ('Suv shisha', 'Sport mashg‘ulotlar uchun qulay shisha', 80000, 7),
       ('Yoga mat', 'Sport va dam olish uchun qulay mat', 150000, 7),
       ('Dumbbell to‘plami', 'Jismoniy mashqlar uchun 2 kg dumbbell', 220000, 7),
       ('Fitness rezina bant', 'Jismoniy mashqlar va streching uchun', 120000, 7),
       ('Sport kiyimi to‘plami', 'Trenajyor va yugurish uchun kiyim', 350000, 7),
       ('Running shoes', 'Yugurish va sport uchun qulay poyabzal', 400000, 7),
       ('Trenajyor velosipedi', 'Uy sharoitida mashq uchun', 950000, 7),
       ('Skateboard', 'Sport va ko‘ngil ocharlik uchun', 450000, 7),
       ('Sport sumkasi', 'Trenajyor va sport jihozlarini saqlash uchun', 180000, 7),
       ('Kickboxing qo‘lqopi', 'Sport mashg‘ulotlari uchun xavfsiz qo‘lqop', 200000, 7),
       ('Suvenir dumbbell', 'O‘yin va dekorativ maqsad uchun', 100000, 7),
       ('Dunyo tarixi', 'Ilmiy va ommabop dunyo tarixi kitobi', 150000, 8),
       ('Matematika asoslari', 'O‘quvchilar uchun matematika darsligi', 90000, 8),
       ('Python dasturlash', 'Boshlovchilar uchun Python dasturlash kitobi', 120000, 8),
       ('C++ dasturlash', 'O‘rta darajadagi dasturchilar uchun', 130000, 8),
       ('O‘zbek adabiyoti', 'Maktab va oliy o‘quv yurtlari uchun adabiyot kitobi', 80000, 8),
       ('Ilm-fan asoslari', 'Kichik yoshdagi bolalar uchun ilm-fan kitobi', 70000, 8),
       ('Biznes va marketing', 'Samarali biznes strategiyalari kitobi', 180000, 8),
       ('Psixologiya asoslari', 'Odam ruhiyati va psixologiya haqida', 140000, 8),
       ('Oziq-ovqat va sog‘lomlik', 'Sog‘lom ovqatlanish bo‘yicha qo‘llanma', 120000, 8),
       ('Roman klassik', 'Dunyo adabiyotidan klassik roman', 160000, 8),
       ('Self-development', 'Shaxsiy rivojlanish va motivatsiya kitobi', 130000, 8),
       ('Ona tili grammatikasi', 'O‘zbek tili grammatikasi darsligi', 90000, 8),
       ('Ilmiy fantastika', 'Bolalar va o‘smirlar uchun fantastika', 100000, 8),
       ('Tarixiy roman', 'Tarixiy voqealarga asoslangan roman', 150000, 8),
       ('Biznes psixologiyasi', 'Korxona va jamoani boshqarish bo‘yicha kitob', 180000, 8),
       ('Elektr tornavida', 'Uy va ofis ishlari uchun qulay elektr tornavida', 450000, 9),
       ('Sement 25kg', 'Qurilish uchun sifatli sement', 120000, 9),
       ('Bo‘yoq 10L', 'Ichki va tashqi devorlarni bo‘yash uchun', 350000, 9),
       ('Gipskarton listi', 'Ichki devorlar va shift uchun', 250000, 9),
       ('Barkamol bolg‘a', 'Qurilish va ta’mirlash ishlari uchun', 90000, 9),
       ('Vintovka va mixlar', 'Qurilish ishlari uchun to‘plam', 80000, 9),
       ('Sichqoncha santexnika', 'Uy santexnikasi va kichik ta’mirlash', 150000, 9),
       ('Qurilish lenta', 'Devor va shift ishlari uchun', 40000, 9),
       ('Elektr kabel 10m', 'Uy va ofis uchun qulay kabel', 120000, 9),
       ('Gidroizolyatsiya materiali', 'Devor va pol uchun suvdan himoya', 250000, 9),
       ('Qurilish sviter', 'Qurilish ishchilari uchun himoya kiyimi', 180000, 9),
       ('Shpatlevka 5kg', 'Devorlarni tekislash uchun', 90000, 9),
       ('O‘lchov lenta', 'Qurilish va ta’mirlash ishlari uchun', 30000, 9),
       ('Alyuminiy skameyka', 'Ta’mirlash va ishlash uchun qulay platforma', 220000, 9),
       ('Elektr drill', 'Qurilish va ta’mirlash ishlari uchun kuchli drill', 500000, 9);



select p.products_name, c.category_name, p.price
from products p
         join categories c on p.category_id = c.id;